---
Name: HtmlEditorField-content-templates
Before: 'mysite/*'
After: 'framework/*','cms/*'
---

SilverStripe\Control\Director:
  rules:
     'getcontenttemplates//$Action/$ID': 'GetContentTemplateData'
