---
Name: canned-content
Before: 'mysite/*'
After: ['framework/*','cms/*']
---

SilverStripe\Control\Director:
  rules:
     'cannedcontent//$Action/$ID': 'Fractas\CannedContent\CannedContentController'
